<?php


namespace app\components;
use yii\base\Widget;


class TestWidget extends Widget
{
    public $name;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->name === null){
            return $this->name = 'Guest';
        }
        ob_start();

    }

    public function run()
    {
        //через ob_start и ob_get_clean управляем содержимым в виджете, можем сделать return так, как нужно
        $content = ob_get_clean();
        $content = strip_tags($content);
        return $this->render('test', [
            'name' => $this->name,
            'content' => $content,
        ]);
        //return "let's test, {$this->name}! {$content}";
    }

}